AA_core/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user_profile.urls')),
    path('projects/sending_emails/', include('project_1_sending_emails.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ----------------------------------------------------------------------------------------------------------------------
# HTTP STATUS

# Bad Request
handler400 = "base.views.custom_400"
# Unauthorized
handler401 = "base.views.custom_401"
# Forbidden
handler403 = "base.views.custom_403"
# Not Found
handler404 = 'base.views.custom_404'
# Internal Server Error
handler500 = "base.views.custom_500"
# Internal Server Error
handler502 = "base.views.custom_502"
# Service Unavailable
handler503 = "base.views.custom_503"
# Gateway Timeout
handler504 = "base.views.custom_504"
# ----------------------------------------------------------------------------------------------------------------------

base/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('',  views.redirect_to_url_main_page, name=''),
    path('main_page/', views.main_page, name='main_page'),
    path('about_me/', views.redirect_to_url_main_page, name='about_me'),
    path('about_me/education/', views.about_me_education, name='about_me_education'),
    path('about_me/education/grades/<int:pk>/', views.EducationDetail.as_view(), name='education'),
    path('about_me/skills/', views.about_me_skills, name='about_me_skills'),
    path('contacts/', views.contacts, name='contacts'),
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = "user_profile"


urlpatterns = [
    path('',  views.redirect_to_url_main_page, name=''),
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path("logout/", views.logout_request, name="logout"),
    path('profile/<username>/', views.profile, name='profile'),
]

base/models.py
from django.db import models
from parler.models import TranslatableModel, TranslatedFields
from django.core.validators import MaxValueValidator, MinValueValidator


class MenuLevTwo(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=90, blank=True,),
        address=models.CharField(max_length=90, default="#"),
    )

    def __str__(self):
        return self.name


class MenuLevOne(TranslatableModel):
    menu_two = models.ManyToManyField(MenuLevTwo, blank=True, )
    translations = TranslatedFields(
        name=models.CharField(max_length=90, blank=True,),
        address=models.CharField(max_length=90, default="#", blank=True,),
    )

    def __str__(self):
        return self.name


class Base(TranslatableModel):
    menu_one = models.ManyToManyField(MenuLevOne, blank=True, )
    translations = TranslatedFields(
        title=models.CharField(max_length=90, blank=True,),
        name_menu=models.CharField(max_length=90, blank=True,),
    )

    def __str__(self):
        return self.title


class ContentBody(TranslatableModel):
    translations = TranslatedFields(
        title=models.CharField(max_length=90, blank=True,),
        data_json=models.JSONField(blank=True, null=True)
    )

    def __str__(self):
        return self.title


class Education(TranslatableModel):

    translations = TranslatedFields(
        name=models.CharField(max_length=300, blank=True,),
        degree=models.CharField(max_length=90, blank=True,),
        specialty=models.CharField(max_length=90, blank=True,),
        city=models.CharField(max_length=90, blank=True,),
        country=models.CharField(max_length=90, blank=True,),
        name_diploma_project=models.CharField(max_length=300, blank=True,),
    )
    grade_diploma_project = models.IntegerField(default=1, blank=True, )
    learn_start = models.DateField(blank=True, null=True)
    learn_end = models.DateField(blank=True, null=True)
    # 2048 – it is max length url
    url_to_photo_diploma = models.CharField(max_length=2048, blank=True,)
    max_amount = models.IntegerField(
        default=100,)

    class Meta:
        ordering = ('-learn_end',)

    def __str__(self):
        return self.name+" ("+self.degree+")"


class GradeEducation(TranslatableModel):
    amount = models.IntegerField(
        default=1,
        validators=[
            MaxValueValidator(100),
            MinValueValidator(1),
        ],
        blank=True,
    )
    education = models.ForeignKey(Education, on_delete=models.CASCADE, blank=True, null=True)
    translations = TranslatedFields(
        name=models.CharField(max_length=90, blank=True,),
        commentary=models.CharField(max_length=90, blank=True,),
    )

    def __str__(self):
        return self.name


class ProjectSkills(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=90, blank=True, ),
    )
    link = models.URLField(
        max_length=200,
        db_index=True,
        unique=True,
        blank=True
    )

    def __str__(self):
        return self.name


class TypeSkills(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=90, blank=True, ),
    )

    def __str__(self):
        return self.name


class Skill(TranslatableModel):
    TYPE_CHOICES = (
        ('Base', 'Base'),
        ('Frameworks and libs', 'Frameworks and libs'),
        ('Tools', 'Tools'),
        ('Other', 'Other'),
    )
    img = models.ImageField(upload_to='skills/', blank=True, max_length=500)
    translations = TranslatedFields(
        name=models.CharField(verbose_name="name_90", max_length=90, blank=True, ),
        description=models.CharField(verbose_name="description_100", max_length=100, blank=True, ),
    )
    type_skill = models.ForeignKey(TypeSkills, on_delete=models.CASCADE, blank=True, null=True)
    projects_skill = models.ManyToManyField(ProjectSkills, blank=True, )

    def __str__(self):
        return self.name

    def get_type_choices(self):
        return [choice[0] for choice in self.TYPE_CHOICES]


class MessageContact(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(max_length=400, blank=True,),
    )

    def __str__(self):
        return self.name

base/forms.py
from django import forms


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)

base/views.py
# ---------------------------------------------
# import base django
from django.shortcuts import render, redirect
from django.utils.translation import get_language
from django.utils import translation
from django.views.generic.detail import DetailView
from django.db.models import Avg
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponse
# ---------------------------------------------
# import models
from .models import Base
from .models import ContentBody
from .models import Education, GradeEducation
from .models import Skill, TypeSkills
from .models import MessageContact
# ---------------------------------------------
# import forms
from .forms import ContactForm
# ---------------------------------------------
# import base python
import xml.etree.ElementTree as ET
# ---------------------------------------------


def main_page(request):
    base_entry = Base.objects.first()
    content_body = ContentBody.objects.filter(translations__title="Main Page")[0]
    context = {
        'Base': base_entry,
        "Content_body": content_body,
        'get_last_url': request.path[4:-1],
        'base_data': f'base/js/data/{request.path[1:3]}.js',
    }
    return render(request, 'base/main_page.html', context=context)


def about_me_education(request):
    base_entry = Base.objects.all()[0]
    content_body = ContentBody.objects.filter(translations__title="Education")[0]
    education_base = Education.objects.all()
    context = {
        'Base': base_entry,
        "Content_body": content_body,
        "educations": education_base,
        # request.path[1:3] this is current language. Give from url.
        'content_data': parse(settings.STATIC_ROOT + f'/education/xml/{request.path[1:3]}_content.xml'),
        'get_last_url': request.path[4:-1],
        'base_data': f'base/js/data/{request.path[1:3]}.js',
    }
    return render(request, 'base/about_me/education/education.html', context=context)


class EducationDetail(DetailView):
    model = Education
    context_object_name = "education"
    template_name = 'base/about_me/education/education_detail.html'

    def get_context_data(self, **kwargs):
        detail_education = super(EducationDetail, self).get_context_data(**kwargs)
        base_entry = Base.objects.all()[0]
        content_body = ContentBody.objects.filter(translations__title="Education")[0]
        # detail_education["object"].id is id current Education
        grades = GradeEducation.objects.filter(education__id=detail_education["object"].id).translated('en').order_by("translations__commentary")
        grades_average = round(grades.aggregate(Avg('amount'))["amount__avg"],2)
        context = {
            "Education": detail_education,
            "Base": base_entry,
            "Content_body": content_body,
            "grades": grades,
            "grades_average": grades_average,
            'content_data': parse(settings.STATIC_ROOT + f'/education/xml/grades/{self.request.path[1:3]}_grades.xml'),
            "get_last_url": self.request.path[4:-1],
            'base_data': f'base/js/data/{self.request.path[1:3]}.js',
        }

        return context


def about_me_skills(request):
    base_entry = Base.objects.all()[0]
    content_body = ContentBody.objects.filter(translations__title="Skills")[0]
    skills_base = Skill.objects.translated('en').order_by("id").all()
    skills_type = TypeSkills.objects.all()
    context = {
        'Base': base_entry,
        "Content_body": content_body,
        # request.path[1:3] this is current language. Give from url.
        'content_data': f'skills/js/data/{request.path[1:3]}.js',
        'skills': skills_base,
        'skills_type': skills_type,
        'get_last_url': request.path[4:-1],
        'base_data': f'base/js/data/{request.path[1:3]}.js',
    }
    return render(request, 'base/about_me/skills.html', context=context)


def contacts(request):
    base_entry = Base.objects.all()[0]
    content_body = ContentBody.objects.filter(translations__title="Contacts")[0]
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "[Website 'About me'] [Contact]"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join('{} : {}'.format(key, value) for key, value in body.items())
            messages.info(request,
                          MessageContact.objects.filter(translations__name="Send message!")[0].name)

            try:
                send_mail(subject, message, settings.EMAIL_HOST_USER, ['polozyuk.ser.work@gmail.com'])
            except BadHeaderError:
                return HttpResponse(MessageContact.objects.filter(translations__name=
                                                                "Invalid header found."))
            return redirect("/"+get_language()+'/main_page/')
        else:
            messages.error(request, MessageContact.objects.filter(translations__name=
                                                            "Doesn't send message!"))
    form = ContactForm()
    context = {
        'Base': base_entry,
        "Content_body": content_body,
        'get_last_url': request.path[4:-1],
        'base_data': f'base/js/data/{request.path[1:3]}.js',
        'form': form,
        }

    return render(request, 'base/contacts.html', context=context)


def parse(address):
    xmldoc = ET.parse(address)
    root = xmldoc.getroot()
    xml_dict = {child.tag: child.text for child in root}
    return xml_dict


def redirect_to_url_main_page(request):
    return redirect("/"+get_language()+'/main_page/')


# custom 400 view
def custom_400(request, exception):
    return render(request, 'base/HTTP_status/400.html', status=400)


# custom 401 view
def custom_401(request, exception):
    return render(request, 'base/HTTP_status/401.html', status=401)


# custom 403 view
def custom_403(request, exception):
    return render(request, 'base/HTTP_status/403.html', status=403)


# custom 404 view
def custom_404(request, exception):

    return render(request, 'base/HTTP_status/404.html', status=404)


# custom 500 view
def custom_500(request):
    return render(request, 'base/HTTP_status/500.html', status=500)


# custom 501 view
def custom_501(request):
    return render(request, 'base/HTTP_status/501.html', status=501)


# custom 503 view
def custom_503(request):
    return render(request, 'base/HTTP_status/503.html', status=503)


# custom 504 view
def custom_504(request):
    return render(request, 'base/HTTP_status/504.html', status=504)

templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title> {% block title %} {% endblock %} </title>


    {% load bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

    {% bootstrap_messages %}

    {% load bootstrap_icons %}

    {% block link_css %} {% endblock %}
    <link rel="stylesheet" href="{% static 'base/css/menu.css' %}">


    {% get_current_language as CURRENT_LANGUAGE %}
    {% get_available_languages as AVAILABLE_LANGUAGES %}
    {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
</head>
<body>
<div class="container-fluid">
    <div class="row ">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <span class="fs-5 d-none d-sm-inline">
                        {{ Base.name_menu }}
                    </span>
                <ul class="nav nav-pills flex-column align-items-center align-items-sm-start" id="menu">
                    {% for level_1 in Base.menu_one.all %}
                        <li class="nav-item">
                            {% if level_1.menu_two.all %}
                                <a href="" class="nav-link px-0 align-middle ">
                            {% else %}
                                {% url level_1.address as the_url %}
                                {% if the_url in request.path %}
                                    <a href="{% url level_1.address %}"
                                       class="active-link nav-link px-0 align-middle text-warning">
                                {% else %}
                                    <a href="{% url level_1.address %}" class="nav-link px-0 align-middle">
                                {% endif %}
                            {% endif %}
                            <i class="fs-4 bi-speedometer2"></i>
                            <span class="ms-1 d-none d-sm-inline ">
                                    {{ level_1 }}
                                </span>
                            </a>
                        </li>
                        <ul class=" nav flex-column ms-1 " id="submenu{{ level_1.id }}" data-bs-parent="#menu">
                            {% for level_2 in level_1.menu_two.all %}
                                <li class="w-100">
                                    {% url level_2.address as the_url %}
                                    {% if the_url in request.path %}
                                        <a href="{% url level_2.address %}" class="active-link nav-link px-10 ">
                                            {{ level_2.name }}
                                        </a>
                                    {% else %}
                                        <a href="{% url level_2.address %}" class="nav-link px-10">
                                            {{ level_2.name }}
                                        </a>
                                    {% endif %}
                                </li>
                            {% endfor %}
                        </ul>
                    {% endfor %}
                    <li>
                            <span class="ms-1 d-none d-sm-inline">
                                <select class="selectpicker form-select bg-dark text-white text-decoration-none"
                                        data-width="fit" onchange="location = this.value;">
                                    {% for language in languages %}
                                        <option
                                                {% if language.code == CURRENT_LANGUAGE %} selected{% endif %}
                                                                                           value="/{{ language.code }}/{{ get_last_url }}/">
                                            {{ language.name_local }} </option>
                                    {% endfor %}
                                </select>
                            </span>
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link px-0 align-middle " href="{% url 'user_profile:logout' %}"
                                   id="Link_Logout_Base">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link px-0 align-middle" id="Login_Welcome"
                                   href="{% url 'user_profile:profile' user.username%}">, {{ user.first_name }} {{ user.last_name }}
                                </a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link px-0 align-middle " href="{% url 'user_profile:register' %}"
                                  id="Link_Register_Base">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link px-0 align-middle " href="{% url 'user_profile:login' %}"
                                   id="Link_Login_Base">
                                </a>
                            </li>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
        {% block content %}

        {% endblock %}
    </div>
</div>
</div>

{% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}

{% block link_js %} {% endblock %}
<script type="text/javascript" src="{% static "" %}{{ base_data }}"></script>
<script type="text/javascript" src="{% static "base/js/data/general.js" %}"></script>
</body>
</html>